### ISSUE TITLE
saved 기능 구현

### ISSUE THREAD

**Issue by skojphy** [TeamCooks/hanspoon#66]
## 🌟 Description
save 버튼 클릭 시 saved 수를 DB에 저장하는 기능을 구현할 예정입니다.

## 📌 List
구현하거나 해야 할 목록을 아래 양식으로 작성해주세요.
- [x] save 버튼 이벤트 등록
- [x] saved 상태 관리
- [x] DB 연결

**Comment by hhhyyo** [comment]
#70 파이어베이스에 연결했습니다.
